## Numpy

Mirar los videos que están en la plataforma de Acámica y tratar de resolver los siguientes ejercicios y preguntas. La documentación de Numpy es muy buena, recomendamos ir familiarizándose con ella.

### Repaso

Importamos la librería

In [1]:
import numpy as np
lista = [1,2,3,4,5,6]
lista + [2]

[1, 2, 3, 4, 5, 6, 2]

In [2]:
whos

Variable   Type      Data/Info
------------------------------
lista      list      n=6
np         module    <module 'numpy' from 'C:\<...>ges\\numpy\\__init__.py'>


In [3]:
matriz = [[1,2,3], [1,2,3], [1,2,3]]

In [4]:
matriz


[[1, 2, 3], [1, 2, 3], [1, 2, 3]]

In [5]:
whos

Variable   Type      Data/Info
------------------------------
lista      list      n=6
matriz     list      n=3
np         module    <module 'numpy' from 'C:\<...>ges\\numpy\\__init__.py'>


A partir de una lista podemos crear un arreglo de numpy

In [6]:
[lista, lista]

[[1, 2, 3, 4, 5, 6], [1, 2, 3, 4, 5, 6]]

In [7]:
[lista, lista]

[[1, 2, 3, 4, 5, 6], [1, 2, 3, 4, 5, 6]]

In [8]:
arreglo = np.arange(1, 10, 2)

In [9]:
arreglo

array([1, 3, 5, 7, 9])

In [10]:
a = np.arange(100).reshape((2,10,5))

In [11]:
a

array([[[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19],
        [20, 21, 22, 23, 24],
        [25, 26, 27, 28, 29],
        [30, 31, 32, 33, 34],
        [35, 36, 37, 38, 39],
        [40, 41, 42, 43, 44],
        [45, 46, 47, 48, 49]],

       [[50, 51, 52, 53, 54],
        [55, 56, 57, 58, 59],
        [60, 61, 62, 63, 64],
        [65, 66, 67, 68, 69],
        [70, 71, 72, 73, 74],
        [75, 76, 77, 78, 79],
        [80, 81, 82, 83, 84],
        [85, 86, 87, 88, 89],
        [90, 91, 92, 93, 94],
        [95, 96, 97, 98, 99]]])

In [12]:
lista = [0,1,2,3,4,5]
arreglo = np.array([[lista, lista], [lista, lista]])
print(lista)
print(arreglo)

[0, 1, 2, 3, 4, 5]
[[[0 1 2 3 4 5]
  [0 1 2 3 4 5]]

 [[0 1 2 3 4 5]
  [0 1 2 3 4 5]]]


In [13]:
arreglo.shape

(2, 2, 6)

Pero para algunos casos numpy tiene funciones que crean listas más rápidamente.

In [14]:
arreglo = np.arange(6)
print(arreglo)

[0 1 2 3 4 5]


Algunas cosas que no se podían hacer con las listas ahora sí se pueden:

1. Sumarle un mismo elemento a toda la lista

In [15]:
lista + 1

TypeError: can only concatenate list (not "int") to list

In [16]:
arreglo + 2

array([2, 3, 4, 5, 6, 7])

2. Elevar al cuadrado todos los elementos de una lista

In [17]:
lista**2

TypeError: unsupported operand type(s) for ** or pow(): 'list' and 'int'

In [18]:
arreglo**2

array([ 0,  1,  4,  9, 16, 25], dtype=int32)

### Memoria y Velocidad

In [18]:
import time

In [20]:

%%time
L1 = range(100000)
L2 = range(100000)

A1 = np.arange(100000)
A2 = np.arange(100000)

s = time.time()
%time [a1+a2 for a1, a2 in zip(L1,L2)]
#print('python list:', time.time()-s)


s = time.time()
%time [L1[i]+L2[i] for i in range(len(L1))]
#print('python list:', time.time()-s)


s = time.time()
%time A1+A2
#print('numpy array:', time.time()-s)


Wall time: 9.97 ms
Wall time: 29 ms
Wall time: 0 ns
Wall time: 43.9 ms


array([     0,      2,      4, ..., 199994, 199996, 199998])

In [21]:
time.time()

1600635741.9533238

In [22]:
a = np.linspace(1,30,1000).reshape((500,2))

In [23]:
a

array([[ 1.        ,  1.02902903],
       [ 1.05805806,  1.08708709],
       [ 1.11611612,  1.14514515],
       [ 1.17417417,  1.2032032 ],
       [ 1.23223223,  1.26126126],
       [ 1.29029029,  1.31931932],
       [ 1.34834835,  1.37737738],
       [ 1.40640641,  1.43543544],
       [ 1.46446446,  1.49349349],
       [ 1.52252252,  1.55155155],
       [ 1.58058058,  1.60960961],
       [ 1.63863864,  1.66766767],
       [ 1.6966967 ,  1.72572573],
       [ 1.75475475,  1.78378378],
       [ 1.81281281,  1.84184184],
       [ 1.87087087,  1.8998999 ],
       [ 1.92892893,  1.95795796],
       [ 1.98698699,  2.01601602],
       [ 2.04504505,  2.07407407],
       [ 2.1031031 ,  2.13213213],
       [ 2.16116116,  2.19019019],
       [ 2.21921922,  2.24824825],
       [ 2.27727728,  2.30630631],
       [ 2.33533534,  2.36436436],
       [ 2.39339339,  2.42242242],
       [ 2.45145145,  2.48048048],
       [ 2.50950951,  2.53853854],
       [ 2.56756757,  2.5965966 ],
       [ 2.62562563,

**Ejercicio 1**: Responder las siguientes preguntas:
* ¿Qué operaciones se pueden hacer tanto en un arreglo de Numpy como en una lista? Dar un ejemplo en una celda.
* ¿Qué operaciones se pueden hacer en un arreglo de Numpy pero NO en una lista? Explorar algunas opciones y dar un ejemplo en una celda.
* ¿Cuál es la diferencia entre un arreglo de forma -shape- (n,), (n,1) y (1,n)? Pueden crear arreglos para intentar responder esa pregunta.

In [24]:
#operaciones que se pueden realizar con una lista y un arreglo
a=[1,2,3,4]
b=np.arange(4)
print(a[0]) #indexado
print(b[0])

print(a[0:2]) # funcion corte
print(b[0:2])


1
0
[1, 2]
[0 1]


In [25]:
#operaciones se pueden hacer en un arreglo de Numpy pero NO en una lista
print(np.mean(b)) # se obtiene el promedio de un array
print(np.sum(b)) # suma de los elementos de un vector

1.5
6


In [26]:
#Cuál es la diferencia entre un arreglo de forma -shape- (n,), (n,1) y (1,n)?
import numpy as np
a=np.arange(10)
print(a)
a.shape=(10,1)
print(a)
a.shape=(1,10)
print(a)

[0 1 2 3 4 5 6 7 8 9]
[[0]
 [1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]
 [8]
 [9]]
[[0 1 2 3 4 5 6 7 8 9]]


**Ejercicio 2**:
* Escribir un arreglo con números enteros del 0 al 9. Pista: arange
* Escribir un arreglo con 100 números equiespaciados del 0 al 9. Pista: linspace

In [27]:
arreglo1=np.arange(0,10)
arreglo1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [28]:
arreglo2=np.linspace(0,9,100)
arreglo2

array([0.        , 0.09090909, 0.18181818, 0.27272727, 0.36363636,
       0.45454545, 0.54545455, 0.63636364, 0.72727273, 0.81818182,
       0.90909091, 1.        , 1.09090909, 1.18181818, 1.27272727,
       1.36363636, 1.45454545, 1.54545455, 1.63636364, 1.72727273,
       1.81818182, 1.90909091, 2.        , 2.09090909, 2.18181818,
       2.27272727, 2.36363636, 2.45454545, 2.54545455, 2.63636364,
       2.72727273, 2.81818182, 2.90909091, 3.        , 3.09090909,
       3.18181818, 3.27272727, 3.36363636, 3.45454545, 3.54545455,
       3.63636364, 3.72727273, 3.81818182, 3.90909091, 4.        ,
       4.09090909, 4.18181818, 4.27272727, 4.36363636, 4.45454545,
       4.54545455, 4.63636364, 4.72727273, 4.81818182, 4.90909091,
       5.        , 5.09090909, 5.18181818, 5.27272727, 5.36363636,
       5.45454545, 5.54545455, 5.63636364, 5.72727273, 5.81818182,
       5.90909091, 6.        , 6.09090909, 6.18181818, 6.27272727,
       6.36363636, 6.45454545, 6.54545455, 6.63636364, 6.72727

**Ejercicio 3**:
* Escribir un arreglo con números enteros del 10 al 100 y seleccionar aquellos que son menores que 50.

In [29]:
import numpy as np
a = np.arange(10,100)
a*(a<50)
print(a) # hago una mascara con un valor booleano
a[np.nonzero(a)] #operador nonzero


[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50 51 52 53 54 55 56 57
 58 59 60 61 62 63 64 65 66 67 68 69 70 71 72 73 74 75 76 77 78 79 80 81
 82 83 84 85 86 87 88 89 90 91 92 93 94 95 96 97 98 99]


array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60,
       61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77,
       78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94,
       95, 96, 97, 98, 99])

**Ejercicio 4**:
* Crear un arreglo de ceros de `shape` (5,10).
* Reemplazar la segunda y cuarta fila con unos
* Reemplazar la tercera y octava columna con dos (2).

In [30]:
arreglo1=np.zeros(50)
arreglo1.shape=(5,10)
arreglo1[1:2]=1  # reemplazo filas
arreglo1[3:4]=1
arreglo1[ :,2:3]=2   # reemplazo columnas
arreglo1[ :,7:8]=2
arreglo1


array([[0., 0., 2., 0., 0., 0., 0., 2., 0., 0.],
       [1., 1., 2., 1., 1., 1., 1., 2., 1., 1.],
       [0., 0., 2., 0., 0., 0., 0., 2., 0., 0.],
       [1., 1., 2., 1., 1., 1., 1., 2., 1., 1.],
       [0., 0., 2., 0., 0., 0., 0., 2., 0., 0.]])

In [31]:
# arreglo1[1:4:2,:]

**Ejercicio $\infty$**:
Hacer todos los ejercicios que puedan del siguiente link https://www.machinelearningplus.com/python/101-numpy-exercises-python/

O de https://github.com/rougier/numpy-100