In [1]:
#practica con libreria numpy
import numpy as np
a=np.zeros([2,3]) # se crea una matriz de ceros
print(a)

[[0. 0. 0.]
 [0. 0. 0.]]


In [2]:
# creamos un vector y una matriz
a=np.array([1,2,3])
print("vector")
print(a)
b=np.array([(1,2,3),(4,5,6)])
print("matrix")
print(b)

vector
[1 2 3]
matrix
[[1 2 3]
 [4 5 6]]


In [3]:
# porque usar array y no listas? 
# USAN MENOS ESPACIO
#tambien es mas rápido
import sys
s=range(1000)
print("Resultado lista de Python")
print(sys.getsizeof(5)*len(s))
print()
d=np.arange(1000)#crea un array en el rango de valores dados
print("Resultado lib de Numpy")
print(d.size*d.itemsize)
print()


Resultado lista de Python
28000

Resultado lib de Numpy
4000



In [4]:
#se puede crear también una matriz de unos
a=np.ones((2,3))
print(a)

[[1. 1. 1.]
 [1. 1. 1.]]


In [5]:
#con el comando linespace se crea un arreglo específico espacio igual
a=np.linspace(1,4,6)# crea un arreglo de 6 valores entre el 1 y el 4
print(a)

[1.  1.6 2.2 2.8 3.4 4. ]


In [6]:
#Slicing de una matriz
a=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(a)


[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [7]:
#tomo solo 2 filas
a[:2]

array([[1, 2, 3],
       [4, 5, 6]])

In [8]:
a[:2,1:]

array([[2, 3],
       [5, 6]])

In [9]:
#seleccion de un elemento particular
print(a[1][2])

6


In [10]:
array=np.arange(10,100)# creo un array de 10 a 100

In [11]:
array

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60,
       61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77,
       78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94,
       95, 96, 97, 98, 99])

In [13]:
array1=np.arange(30).reshape(3,10)
print(array1)

[[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]
 [20 21 22 23 24 25 26 27 28 29]]


Ejercicios de la siguiente pagina : https://www.machinelearningplus.com/python/101-numpy-exercises-python/

In [14]:
#3- Create a 3×3 numpy array of all True’s
np.ones((3,3), dtype=bool) #dtypedata-type, optional
 #The desired data-type for the array, e.g., numpy.int8. Default is numpy.float64.

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

In [21]:
#4-Extract all odd numbers from arr
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
arr_imp=[]
for i in range(len(arr)):
    if arr[i] % 2 !=0 :
        arr_imp.append(arr[i])
print(arr_imp)
     
# mejor solucion
# arr[arr % 2 == 1]


[1, 3, 5, 7, 9]


In [24]:
#5- Replace all odd numbers in arr with -1
for i in range(len(arr)):
    if arr[i] % 2 !=0 :
        arr[i]=-1
print(arr)        

[ 0 -1  2 -1  4 -1  6 -1  8 -1]
